apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: jromankiew/auth
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: password
            - name: DB_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-db-config
                  key: DB_DB
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-db-config
                  key: DB_HOST
            - name: DB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: auth-db-config
                  key: DB_TABLE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-db-config
                  key: DB_PORT
            - name: SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: auth-db-config
                  key: SSL_MODE
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
