apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-config
data:
  auth-db-url: auth-db-service
  DB_DB: "postgres"
  POSTGRES_DB: "postgres"
  DB_HOST: "auth-db-service"
  DB_TABLE: "postgres"
  DB_PORT: "5432"
  SSL_MODE: "disable"
