apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/fullstack: "true"
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: DB_DB
              value: postgres
            - name: DB_HOST
              value: auth_db
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_TABLE
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: SSL_MODE
              value: disable
          image: auth
          name: auth-rest-api
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
