apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: jromankiew/profile
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: profile-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profile-db-secret
                  key: password
            - name: DB_DB
              valueFrom:
                configMapKeyRef:
                  name: profile-db-config
                  key: DB_DB
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: profile-db-config
                  key: DB_HOST
            - name: DB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: profile-db-config
                  key: DB_TABLE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: profile-db-config
                  key: DB_PORT
            - name: SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: profile-db-config
                  key: SSL_MODE
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: NodePort
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30101
